#!/bin/bash
# 多范围随机化 - 实际使用示例

echo "=========================================="
echo "多范围随机化 - 实际使用示例"
echo "=========================================="
echo ""

echo "【示例1】保留前后，随机化中间"
echo "假设你想保留开头的0-10和结尾的370-383，随机化中间部分"
echo ""
echo "命令："
echo "python3 randomize_tokens.py \\"
echo "    input.json output.json \\"
echo "    --mode multi-range \\"
echo "    --ranges \"11-369\""
echo ""

echo "【示例2】随机化四个均匀分布的区域"
echo "将384个位置分成4个区域，每个区域96个位置"
echo ""
echo "命令："
echo "python3 randomize_tokens.py \\"
echo "    input.json output.json \\"
echo "    --mode multi-range \\"
echo "    --ranges \"0-95,96-191,192-287,288-383\""
echo ""

echo "【示例3】保留关键特征位置"
echo "假设位置50-60和位置150-160是关键特征，需要保留"
echo "随机化其他所有位置"
echo ""
echo "命令："
echo "python3 randomize_tokens.py \\"
echo "    input.json output.json \\"
echo "    --mode multi-range \\"
echo "    --ranges \"0-49,61-149,161-383\""
echo ""

echo "【示例4】你的实际需求"
echo "随机化位置 2-60, 200-270, 300-320, 350-383"
echo ""
echo "命令："
echo "python3 randomize_tokens.py \\"
echo "    data_test/eval_traj_100.json \\"
echo "    output.json \\"
echo "    --mode multi-range \\"
echo "    --ranges \"2-60,200-270,300-320,350-383\" \\"
echo "    --seed 42"
echo ""

echo "【示例5】批量处理整个目录"
echo "对data_test目录下的所有JSON文件应用相同的多范围随机化"
echo ""
echo "命令："
echo "./batch_randomize.sh \\"
echo "    data_test/ \\"
echo "    output/ \\"
echo "    multi-range \\"
echo "    --ranges \"2-60,200-270,300-320,350-383\" \\"
echo "    --seed 42"
echo ""

echo "【示例6】自定义随机数范围"
echo "如果你想让随机数在特定范围内，比如[5000, 12000]"
echo ""
echo "命令："
echo "python3 randomize_tokens.py \\"
echo "    input.json output.json \\"
echo "    --mode multi-range \\"
echo "    --ranges \"2-60,200-270,300-320,350-383\" \\"
echo "    --min 5000 \\"
echo "    --max 12000"
echo ""

echo "【示例7】范围可以重叠（自动去重）"
echo "如果你指定的范围有重叠，系统会自动去重"
echo ""
echo "命令："
echo "python3 randomize_tokens.py \\"
echo "    input.json output.json \\"
echo "    --mode multi-range \\"
echo "    --ranges \"0-100,50-150,100-200\""
echo ""
echo "实际效果：位置0-200都会被随机化（重叠部分只处理一次）"
echo ""

echo "=========================================="
echo "【验证结果】"
echo "=========================================="
echo ""
echo "处理完成后，可以使用验证脚本检查结果："
echo ""
echo "python3 verify_multi_range.py"
echo ""
echo "或者手动检查："
echo "python3 -c \"import json, re; \\"
echo "data=json.load(open('output.json')); \\"
echo "tokens=re.findall(r'<\|\\\\d+\|>', list(data.values())[0]); \\"
echo "print(f'Token总数: {len(tokens)}')\""
echo ""

echo "=========================================="
