#!/bin/bash
# 实际使用示例：展示如何处理你的数据

echo "=========================================="
echo "实际使用示例"
echo "=========================================="
echo ""

echo "假设你有一个大的数据集需要处理，以下是推荐的工作流程："
echo ""

echo "【步骤1】先在测试数据上验证"
echo "----------------------------------------"
echo "python3 randomize_tokens.py \\"
echo "    data_test/eval_traj_100.json \\"
echo "    test_output.json \\"
echo "    --mode all \\"
echo "    --seed 42"
echo ""

echo "【步骤2】验证输出是否正确"
echo "----------------------------------------"
echo "# 检查token数量"
echo "python3 -c \"import json, re; data=json.load(open('test_output.json')); print('Token数量:', len(re.findall(r'<\|\\d+\|>', list(data.values())[0])))\""
echo ""

echo "【步骤3】批量处理所有文件"
echo "----------------------------------------"
echo "./batch_randomize.sh data_test/ final_output/ all --seed 42"
echo ""

echo "【步骤4】根据需求选择不同的模式"
echo "----------------------------------------"
echo ""
echo "场景A：完全随机化（用于数据增强）"
echo "  ./batch_randomize.sh data/ output/ all"
echo ""
echo "场景B：只随机化前100个位置（保留后面的特征）"
echo "  ./batch_randomize.sh data/ output/ range --start 0 --end 99"
echo ""
echo "场景C：只随机化中间部分（保留开头和结尾）"
echo "  ./batch_randomize.sh data/ output/ range --start 100 --end 283"
echo ""
echo "场景D：随机化多个不连续的区域"
echo "  # 第一次：随机化位置0-50"
echo "  ./batch_randomize.sh data/ temp1/ range --start 0 --end 50"
echo "  # 第二次：随机化位置100-150"
echo "  ./batch_randomize.sh temp1/ temp2/ range --start 100 --end 150"
echo "  # 第三次：随机化位置200-250"
echo "  ./batch_randomize.sh temp2/ final/ range --start 200 --end 250"
echo ""

echo "=========================================="
echo "【重要提示】"
echo "=========================================="
echo ""
echo "1. 建议先在小数据集上测试，确认结果符合预期"
echo "2. 使用 --seed 参数可以保证结果可重复"
echo "3. 处理大量文件前，建议先备份原始数据"
echo "4. 可以使用 verify_output.py 验证处理结果"
echo ""

echo "=========================================="
echo "【性能提示】"
echo "=========================================="
echo ""
echo "如果需要处理大量文件，可以使用并行处理："
echo ""
echo "# 使用GNU parallel（如果已安装）"
echo "ls data/*.json | parallel python3 randomize_tokens.py {} output/{/} --mode all"
echo ""
echo "# 或者使用xargs"
echo "ls data/*.json | xargs -P 4 -I {} python3 randomize_tokens.py {} output/{} --mode all"
echo ""

echo "=========================================="
